server:
  port: 8123
  servlet:
    context-path: /api

spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd'T'HH:mm:ss
  application:
    name: picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: REDACTED_KNIFE4J_PASSWORD
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: local
  redis:
    host: 192.168.200.100
    port: 6379
    database: 0
    timeout: 3000ms

sa-token:
  # jwt秘钥
  jwt-secret-key: REDACTED_JWT_SECRET
  timeout: 360000
  token-name: sa_token

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    # 开发环境下开启日志
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# swagger增强knife4j
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xin.picturebackend.controller

# 日志级别修改
logging:
  level:
    com.xin.picturebackend: debug

# 自定义 app 配置, 并未设置默认值，不可删除任意项。
app:
  hotkey:
    detect:
      threshold: 100
      maxCapacity: 1000
      expireSec: 10
  rateLimiter:
    defaultPermitsPerSecond: 3.0
    expireAfterAccess: 600
    maximumSize: 100000
  script:
    lua:
      deleteByRefreshToken:
        path: "lua/delete_refresh_and_reverse.lua"
      deleteByUserIdToken:
        path: "lua/delete_by_userid.lua"
  cookies:
    cookieConfigs:
      refreshToken:
        name: re_token
        max-age: 864000
        path: "/api/user/auth/refresh"
        http-only: true
        same-site: "Lax"
      onceToken:
        name: sec_token
        max-age: 240
        path: "/"
