server:
  port: 8123
  servlet:
    context-path: /api

spring:
  rabbitmq:
    host: 192.168.200.100           # RabbitMQ 主机地址
    port: 5672                # 默认端口
    username: admin           # 登录用户名（建议换成自己的）
    password: REDACTED_RMQ_DEV_PASSWORD           # 登录密码
    virtual-host: /           # 虚拟主机（可按需自定义）
    template:
      exchange: x.message.direct
    listener:
      simple:
        concurrency: 2        # 最小并发消费者数
        max-concurrency: 3   # 最大并发消费者数
        prefetch: 1           # 每次只拉取一个消息
        acknowledge-mode: auto
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd'T'HH:mm:ss
  application:
    name: picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: REDACTED_KNIFE4J_PASSWORD
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 4MB
  redis:
    host: 192.168.200.100
    port: 6379
    database: 0
    timeout: 3000ms
  profiles:
    active: local
  mail:
    host: smtp.qq.com
    port: 465
    username: 3306019801@qq.com
    password: REDACTED_EMAIL_PASSWORD
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

sa-token:
  # jwt秘钥
  jwt-secret-key: REDACTED_JWT_SECRET
  timeout: 360000
  token-name: sa_token

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    # 开发环境下开启日志
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# swagger增强knife4j
knife4j:
  enable: true
  basic:
    username: root
    password: REDACTED_KNIFE4J_PASSWORD

# 日志级别修改
logging:
  level:
    com.xin.picturebackend: debug

# 自定义 app 配置, 并未设置默认值，不可删除任意项。
app:
  name: 图协空间
  heartbeat: 120 # websocket 心跳
  hotkey:
    detect:
      threshold: 100
      maxCapacity: 1000
      expireSec: 10
  rateLimiter:
    defaultPermitsPerSecond: 3.0
    expireAfterAccess: 600
    maximumSize: 100000
  script:
    lua:
      deleteByRefreshToken:
        path: "lua/delete_refresh_and_reverse.lua"
      deleteByUserIdToken:
        path: "lua/delete_by_userid.lua"
  cookies:
    cookieConfigs:
      refreshToken:
        name: re_token
        max-age: 864000
        path: "/api/user/auth/refresh"
        http-only: true
        same-site: "Lax"
      onceToken:
        name: sec_token
        max-age: 240
        path: "/"
  retry:
    event:
      max: 3
  email-code:
    max-sends-per-period: 3
    send-limit-expire-minutes: 15
    code-length: 6
    send-cooldown-seconds: 60
    code-expire-minutes: 5
    validate-fail-count-expire-minutes: 3
    max-validate-fail-count: 15